# Generated by Django 4.2.5 on 2023-09-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_adresse_datum_alter_artikel_preis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='datum',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
